language: node_js

node_js:
  - '6'
  - 'lts/*'
  - 'node'

install:
  - npm install

script:
  - npm run lint
  - npm test
  - npm run report

after_script: "npm install coveralls && cat ./coverage/lcov.info | coveralls"

sudo: false
